# Generated by Django 3.2.8 on 2021-12-25 06:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodType',
            fields=[
                ('BloodTypeId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bloodType', models.CharField(default='Name', max_length=30)),
                ('cdate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'BloodType',
            },
        ),
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('UserId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Email', models.EmailField(default='admin@info.com', max_length=254)),
                ('Name', models.CharField(default='Name', max_length=30)),
                ('UserName', models.CharField(default='User Name', max_length=12)),
                ('Password', models.CharField(default='password', max_length=12)),
                ('Address', models.TextField()),
                ('PublickTocken', models.CharField(default='password', max_length=100)),
                ('PriventTocken', models.CharField(default='password', max_length=100)),
                ('Update', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('Createdate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'ClientUsers',
            },
        ),
        migrations.CreateModel(
            name='Diagnostics',
            fields=[
                ('DId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('DName', models.CharField(default='', max_length=500)),
                ('DCty', models.CharField(default='', max_length=500)),
                ('DAB', models.CharField(default='', max_length=500)),
                ('Desicription', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'dignostics',
            },
        ),
        migrations.CreateModel(
            name='Docterreferrence',
            fields=[
                ('RFId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(default='', max_length=500)),
                ('Pho', models.BigIntegerField()),
                ('Department', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'verbose_name_plural': 'refdetails',
            },
        ),
        migrations.CreateModel(
            name='medsDeatils',
            fields=[
                ('MId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('MName', models.CharField(default='', max_length=500)),
                ('MAB', models.CharField(default='', max_length=500)),
                ('MComapnyName', models.CharField(default='', max_length=500)),
                ('Update', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('Createdate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('Remarks', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'medsDetails',
            },
        ),
        migrations.CreateModel(
            name='PatientDetails',
            fields=[
                ('patient_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstName', models.CharField(default='First Name', max_length=100)),
                ('lastName', models.CharField(blank=True, default='Last Name', max_length=100)),
                ('gender', models.CharField(default='Not intrested to share', max_length=30)),
                ('dob', models.DateField(default=django.utils.timezone.now)),
                ('heigth', models.BigIntegerField(blank=True, default=0.0)),
                ('weigth', models.BigIntegerField(blank=True, default=0.0)),
                ('phoneNumber', models.BigIntegerField(default=9999999999)),
                ('emailAddress', models.EmailField(default='user@prescriptionpad.in', max_length=254)),
                ('Update', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('Createdate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('bloodType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='AouthIO.bloodtype')),
            ],
            options={
                'verbose_name_plural': 'PatientDetails',
            },
        ),
        migrations.CreateModel(
            name='PRBase',
            fields=[
                ('Bid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Update', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('Createdate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('RFId', models.CharField(blank=True, default='', max_length=1000)),
                ('medical_condition', models.TextField(blank=True)),
                ('refnote', models.TextField(blank=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='AouthIO.patientdetails')),
            ],
            options={
                'verbose_name_plural': 'PRBase',
            },
        ),
        migrations.CreateModel(
            name='PrLabTest',
            fields=[
                ('PRLABID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('labtest', models.CharField(default='', max_length=500)),
                ('Bid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='AouthIO.prbase')),
            ],
            options={
                'verbose_name_plural': 'PrLabTest',
            },
        ),
        migrations.CreateModel(
            name='PrExistingDaignosis',
            fields=[
                ('PREXDIGID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diagnosis', models.TextField(blank=True)),
                ('Bid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='AouthIO.prbase')),
            ],
            options={
                'verbose_name_plural': 'PrExistingDaignosis',
            },
        ),
        migrations.CreateModel(
            name='prescriptionRecords',
            fields=[
                ('PRId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time', models.CharField(default='', max_length=500)),
                ('days', models.BigIntegerField()),
                ('remarks', models.TextField(blank=True)),
                ('Bid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='AouthIO.prbase')),
                ('medicin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='AouthIO.medsdeatils')),
            ],
            options={
                'verbose_name_plural': 'prescriptionRecords',
            },
        ),
        migrations.CreateModel(
            name='PrDaignosis',
            fields=[
                ('PRDIGID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Bid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='AouthIO.prbase')),
                ('DId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='AouthIO.diagnostics')),
            ],
            options={
                'verbose_name_plural': 'PrDaignosis',
            },
        ),
        migrations.CreateModel(
            name='LabTestRecords',
            fields=[
                ('LabRecordId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('LabTestName', models.CharField(blank=True, default='', max_length=1000)),
                ('LabTestDate', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('LabTestResult', models.TextField(blank=True)),
                ('Bid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='AouthIO.prbase')),
            ],
            options={
                'verbose_name_plural': 'LabTestRecords',
            },
        ),
    ]
